"""
build_family_watchlist.py
Picks a few real tickers per vocabulary pack family from the MarketDataLibrary, so each pack can be tested against
more than one company, spanning its different industries where a pack covers several.

    py build_family_watchlist.py                     write watchlists/family_sample.txt
    py build_family_watchlist.py --per-industry 3     more (or fewer) tickers per industry within each pack

Selection is alphabetical by symbol (no market-cap data is pulled here), grouped by pack and industry so the file
is easy to prune or swap by hand before fetching. This does not fetch anything: run batch.py separately when ready.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import vocab

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "watchlists" / "family_sample.txt"


def build(per_industry: int) -> dict[str, dict[str, list[str]]]:
    snapshot: dict[str, dict] = json.loads(vocab.SYMBOL_INDUSTRY_FILE.read_text(encoding="utf-8"))
    mapping = json.loads(vocab.INDUSTRY_PACKS_FILE.read_text(encoding="utf-8"))
    industries, sectors = mapping["industries"], mapping.get("sectors", {})

    by_industry: dict[str, list[str]] = defaultdict(list)
    for symbol, info in snapshot.items():
        ind = info.get("industry")
        if ind:
            by_industry[ind].append(symbol)
    for lst in by_industry.values():
        lst.sort()

    out: dict[str, dict[str, list[str]]] = defaultdict(dict)
    for industry, packs in industries.items():
        for pack in packs:
            out[pack][industry] = by_industry.get(industry, [])[:per_industry]
    # sector-fallback industries have no packs of their own by definition, so sample straight from the sector
    for sector, packs in sectors.items():
        if sector == "note":
            continue
        symbols = sorted(sym for sym, info in snapshot.items()
                         if info.get("sector") == sector and not industries.get(info.get("industry") or ""))
        for pack in packs:
            out[pack][f"({sector}, no specific industry)"] = symbols[:per_industry]
    return out


def write(out: dict[str, dict[str, list[str]]], path: Path) -> None:
    lines = [
        "# Multi-company sample, one block per vocabulary pack (vocabulary/<pack>.json), several industries where a",
        "# pack covers more than one. Generated by build_family_watchlist.py from the MarketDataLibrary; picked",
        "# alphabetically, not by size or liquidity -- prune or swap tickers by hand before fetching.",
        "#",
        "#   py batch.py --season 2026q2 --symbols-file watchlists\\family_sample.txt",
        "#",
        "# Each ticker costs one Alpha Vantage request on first fetch (free tier ~25/day); already-cached calls are",
        "# free on rerun. Nothing here has been fetched yet. Nothing is written to any database.", ""]
    total = 0
    for pack in sorted(out):
        symbols = [s for group in out[pack].values() for s in group]
        if not symbols:
            continue
        lines.append(f"# --- {pack} ({len(symbols)} tickers across {len(out[pack])} industries) ---")
        for industry, group in sorted(out[pack].items()):
            if group:
                lines.append(f"{','.join(group):<40} # {industry}")
        lines.append("")
        total += len(symbols)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {total} ticker mentions across {sum(1 for p in out if any(out[p].values()))} packs -> {path}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-industry", type=int, default=2)
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    if not vocab.SYMBOL_INDUSTRY_FILE.exists():
        print("vocabulary/symbol_industry.json not found; run `py refresh_industries.py` first.", file=sys.stderr)
        return 1
    write(build(args.per_industry), Path(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
